### ISSUE TITLE
Possible issue with css file

### ISSUE THREAD

**Issue by lexicalninja** [webjars/uswds#6]
I know this is probably not a repo you all check super often, but I was using it in a Ktor app and came across something. I may just be dumb, so feel free to let me know if that is the case.

If i bring this webjar into the project, and i install it to assets like this
```kotlin 
fun Application.module() {
    install(Webjars){
        path = "assets"
    }
...
}
```

and in my html header I have this 
```html
<link rel="stylesheet" href="/assets/uswds/uswds.css">
<script src="/assets/uswds/js/uswds-init.min.js"></script>
```

Then something happens when the css is pointing to a file. it seems that the way the webjar is built doesn't get packaged the way the uswds css file assumes. 

I can use any of the css to make components, but places where there should be icons or fonts fail. 
![image](https://user-images.githubusercontent.com/7376126/229831400-7661ace6-efdf-470a-8615-feaccebc0231.png)

it finds the css and the min.js file correctly, but the css is pointing to `../img/usa-icons/info.svg` which resolves to `http://localhost:8080/assets/img/usa-icons/info.svg`  for the icons, which does not exist. HOWEVER, `http://localhost:8080/assets/uswds/img/usa-icons/info.svg` does resolve and show the correct icon. 

I am wondering what is happening to cause this.

First off, am I missing something here that would fix this?
Otherwise, is the webjar not packaging itself correctly for this to work? 
Something else?

I know this is probably not something an active eye is kept on, but if anyone has an idea of what might be happening I would greatly appreciate it.

**Comment by jamesward** [comment]
Thanks for reaching out.  So I think things are packaged correctly. You can see all the files:
https://www.webjars.org/listfiles/uswds/3.0.2

Does it work if you load:
`/assets/uswds/css/uswds.css`

ie I'm not sure why loading `/assets/uswds/uswds.css` works...

**Comment by lexicalninja** [comment]
that worked.

to be honest, I just assumed the webjar package was putting everything at `assets/<pkgname>/<pkgname.css>` and wasn't proven wrong 

also, thanks for pointing out the files, I was looking for that and for some reason my brain never clicked on the files link on the webjars site yesterday while I was fighting this. 

thanks for the lightning fast response
